-- TourAPI 및 데이터 확장 테이블 생성 SQL

-- 1. 장소(Places) 테이블
CREATE TABLE IF NOT EXISTS public.places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    lat DECIMAL(10, 8),
    lng DECIMAL(11, 8),
    category_code VARCHAR(50), -- TourAPI 매핑용 필드
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 이벤트(Events) 테이블
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    lat DECIMAL(10, 8),
    lng DECIMAL(11, 8),
    trust_score DECIMAL(3, 2) DEFAULT 0.50,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 원본 데이터 수집 테이블
CREATE TABLE IF NOT EXISTS public.raw_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(50) NOT NULL, -- 예: 'TOURAPI'
    raw_data JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 이벤트 확장 메타 데이터 테이블 (Foreign Key 참조 포함)
CREATE TABLE IF NOT EXISTS public.events_ext (
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE PRIMARY KEY,
    source VARCHAR(50) NOT NULL,
    ext_id VARCHAR(100), -- TourAPI contentId
    meta JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_places_lat_lng ON public.places(lat, lng);
CREATE INDEX IF NOT EXISTS idx_events_lat_lng ON public.events(lat, lng);
CREATE INDEX IF NOT EXISTS idx_raw_items_source ON public.raw_items(source);
CREATE INDEX IF NOT EXISTS idx_events_ext_ext_id ON public.events_ext(ext_id);
